---
- hosts: web

  vars:
    - v_sitename: ttserg.devops.srwx.net     #It's the common variable!!!
    - php_fpm_version: 7.0                   
    - v_letsencrypt_email: nomail@xez.com

  roles: 
   - nginx
   - php-fpm
   - calc                       #has dependencies
   - letsencrypt
